"use client";

import { useState, useEffect } from "react";
import axios from "axios";
import { useRouter, useParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { useToast } from "@/hooks/use-toast";
import { FileUpload } from "@/components/dropzone";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  ArrowLeft,
  Loader2,
  Calendar,
  Clock,
  Info,
  Tag,
  User,
  Save,
  Video,
  Settings,
  FileImage,
  AlertCircle,
} from "lucide-react";
import { Separator } from "@/components/ui/separator";
import { generateSlug } from "@/utils/slugUtils";

interface EditClassState {
  id: string;
  title: string;
  description?: string;
  startTime: string;
  price: number;
  getPrice: boolean;
  registrationFee: number;
  courseFee: number;
  courseFeeEnabled: boolean;
  registrationEnabled: boolean;
  isOnClassroom?: boolean;
  currentRaga?: string | null;
  currentOrientation?: string | null;
  isActive: boolean;
  thumbnailUrl?: string | null;
  capacity?: number | null;
  recurringClass: boolean;
  hasModules: boolean;
  isFirstModuleFree: boolean;
  sessionDescription?: string | null;
  author?: string | null;
  slug: string;
}

export default function EditZoomClassPage() {
  const router = useRouter();
  const params = useParams();
  const classId = params.id as string;

  const [classData, setClassData] = useState<EditClassState | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [slugManuallyEdited, setSlugManuallyEdited] = useState(false);
  const { toast } = useToast();

  useEffect(() => {
    const fetchClass = async () => {
      try {
        const response = await axios.get(
          `${process.env.NEXT_PUBLIC_API_URL}/zoom-live-class/class/${classId}`,
          { withCredentials: true }
        );

        const classData = response.data.data;
        const formattedData = {
          ...classData,
          getPrice: classData.getPrice || false,
          recurringClass: classData.recurringClass || false,
          hasModules: classData.hasModules || false,
          isFirstModuleFree: classData.isFirstModuleFree || false,
          author: classData.author || "",
        };

        // If slug is exactly the same as the auto-generated one from title,
        // we'll assume it wasn't manually edited
        const autoGeneratedSlug = generateSlug(formattedData.title);
        if (formattedData.slug === autoGeneratedSlug) {
          setSlugManuallyEdited(false);
        } else {
          setSlugManuallyEdited(true);
        }

        setClassData(formattedData);
      } catch (error) {
        console.error("Error fetching class details:", error);
        toast({
          title: "Error",
          description: "Failed to load class details. Please try again.",
          variant: "destructive",
        });
        router.push("/dashboard/zoom");
      } finally {
        setIsLoading(false);
      }
    };

    fetchClass();
  }, [classId, toast, router]);

  const handleImageUpload = (fileUrl: string) => {
    if (classData) {
      setClassData({ ...classData, thumbnailUrl: fileUrl });
    }
  };

  const handleToggleClassroom = async (enabled: boolean) => {
    if (!classData) return;

    try {
      setIsSaving(true);
      await axios.post(
        `${process.env.NEXT_PUBLIC_API_URL}/zoom-live-class/admin/class/${classData.id}/toggle-classroom`,
        { isOnClassroom: enabled },
        { withCredentials: true }
      );

      setClassData({ ...classData, isOnClassroom: enabled });

      toast({
        title: "Success",
        description: `Live class ${
          enabled ? "started" : "stopped"
        } successfully`,
      });
    } catch (error) {
      console.error("Error toggling classroom:", error);
      toast({
        title: "Error",
        description: "Failed to update live class status",
        variant: "destructive",
      });
    } finally {
      setIsSaving(false);
    }
  };

  const updateClass = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!classData) return;

    // Basic validation
    if (
      !classData.title ||
      !classData.startTime ||
      !classData.registrationFee ||
      !classData.courseFee ||
      !classData.thumbnailUrl
    ) {
      toast({
        title: "Validation Error",
        description: "Please fill in all required fields",
        variant: "destructive",
      });
      return;
    }

    setIsSaving(true);

    try {
      await axios.put(
        `${process.env.NEXT_PUBLIC_API_URL}/zoom-live-class/admin/class/${classData.id}`,
        {
          title: classData.title,
          description: classData.description,
          startTime: classData.startTime,
          price: 0,
          getPrice: false,
          registrationFee: parseFloat(classData.registrationFee.toString()),
          courseFee: parseFloat(classData.courseFee.toString()),
          courseFeeEnabled: true,
          registrationEnabled: classData.registrationEnabled,
          currentRaga: classData.currentRaga,
          currentOrientation: classData.currentOrientation,
          isActive: classData.isActive,
          thumbnailUrl: classData.thumbnailUrl,
          capacity: classData.capacity,
          recurringClass: false,
          hasModules: false,
          isFirstModuleFree: false,
          sessionDescription: classData.sessionDescription,
          author: classData.author,
          slug: classData.slug,
        },
        { withCredentials: true }
      );

      toast({
        title: "Success",
        description: "Class updated successfully",
      });

      router.push("/dashboard/zoom");
    } catch (error: any) {
      console.error("Error updating class:", error);
      toast({
        title: "Error",
        description: error.response?.data?.message || "Failed to update class",
        variant: "destructive",
      });
    } finally {
      setIsSaving(false);
    }
  };

  // Function to generate a slug from the title
  const generateSlugFromTitle = (title: string) => {
    return generateSlug(title);
  };

  // Handler for title change that can update the slug
  const handleTitleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newTitle = e.target.value;
    if (!classData) return;

    const newClassData = { ...classData, title: newTitle };

    // Only update slug automatically if it hasn't been manually edited
    if (!slugManuallyEdited) {
      newClassData.slug = generateSlugFromTitle(newTitle);
    }

    setClassData(newClassData);
  };

  // Handler for slug change
  const handleSlugChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!classData) return;

    // Format the slug as it's being typed
    const newSlug = generateSlug(e.target.value);
    setClassData({ ...classData, slug: newSlug });
    setSlugManuallyEdited(true);
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-black text-white p-6">
        <div className="max-w-4xl mx-auto">
          <div className="flex justify-center items-center min-h-[400px]">
            <div className="text-center">
              <Loader2 className="h-12 w-12 animate-spin text-green-400 mx-auto mb-4" />
              <h2 className="text-xl font-semibold text-white mb-2">
                Loading Class Details
              </h2>
              <p className="text-zinc-400">
                Please wait while we fetch the class information...
              </p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (!classData) {
    return (
      <div className="min-h-screen bg-black text-white p-6">
        <div className="max-w-4xl mx-auto">
          <div className="flex justify-center items-center min-h-[400px]">
            <div className="text-center">
              <AlertCircle className="h-12 w-12 text-red-500 mx-auto mb-4" />
              <h2 className="text-xl font-semibold text-white mb-2">
                Class Not Found
              </h2>
              <p className="text-zinc-400 mb-4">
                The class you're looking for doesn't exist or has been removed.
              </p>
              <Button
                onClick={() => router.push("/dashboard/zoom")}
                className="bg-green-600 hover:bg-green-700"
              >
                Back to Live Classes
              </Button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-black text-white p-6">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="flex items-center gap-4 mb-6">
          <Button
            variant="ghost"
            onClick={() => router.back()}
            className="p-0 h-auto text-zinc-400 hover:text-white"
          >
            <ArrowLeft className="h-5 w-5 mr-2" />
            Back to Live Classes
          </Button>
        </div>

        <div className="flex justify-between items-center mb-8">
          <div>
            <h1 className="text-3xl font-bold text-white">Edit Live Class</h1>
            <p className="text-zinc-400 mt-2">
              Update your live trading session details
            </p>
          </div>
          {classData.isOnClassroom && (
            <div className="flex items-center gap-2 px-4 py-2 bg-green-500/20 border border-green-500/30 rounded-lg">
              <div className="w-2 h-2 bg-green-400 rounded-full animate-pulse"></div>
              <span className="text-green-400 font-medium">Live Now</span>
            </div>
          )}
        </div>

        <form onSubmit={updateClass} className="space-y-8">
          {/* Basic Information */}
          <Card className="bg-gradient-to-br from-zinc-900/80 to-black/80 border-zinc-700">
            <CardHeader className="pb-4">
              <CardTitle className="text-xl flex items-center text-white">
                <Info className="h-5 w-5 mr-2 text-blue-400" />
                Class Information
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-2 md:col-span-2">
                  <Label
                    htmlFor="title"
                    className="text-sm font-medium text-zinc-300"
                  >
                    Class Title <span className="text-red-500">*</span>
                  </Label>
                  <Input
                    id="title"
                    name="title"
                    value={classData.title}
                    onChange={handleTitleChange}
                    placeholder="Enter a descriptive title for your class"
                    className="w-full bg-zinc-800 border-zinc-700 text-white placeholder-zinc-400"
                    required
                  />
                </div>

                <div className="space-y-2 md:col-span-2">
                  <Label
                    htmlFor="slug"
                    className="text-sm font-medium text-zinc-300"
                  >
                    URL Slug
                  </Label>
                  <Input
                    id="slug"
                    name="slug"
                    value={classData.slug}
                    onChange={handleSlugChange}
                    placeholder="custom-url-path"
                    className="w-full bg-zinc-800 border-zinc-700 text-white placeholder-zinc-400"
                  />
                  <p className="text-xs text-zinc-500">
                    Custom URL identifier. The slug will auto-update as you type
                    the title unless you manually edit it.
                  </p>
                </div>

                <div className="space-y-2">
                  <Label
                    htmlFor="author"
                    className="text-sm font-medium text-zinc-300"
                  >
                    Meeting Author/Host
                  </Label>
                  <div className="relative">
                    <User className="h-4 w-4 absolute left-3 top-3 text-zinc-500" />
                    <Input
                      id="author"
                      name="author"
                      value={classData.author || ""}
                      onChange={(e) =>
                        setClassData({ ...classData, author: e.target.value })
                      }
                      placeholder="Host name"
                      className="pl-10 bg-zinc-800 border-zinc-700 text-white placeholder-zinc-400"
                    />
                  </div>
                </div>

                <div className="space-y-2">
                  <Label
                    htmlFor="startTime"
                    className="text-sm font-medium text-zinc-300"
                  >
                    Start Time <span className="text-red-500">*</span>
                  </Label>
                  <div className="relative">
                    <Calendar className="h-4 w-4 absolute left-3 top-3 text-zinc-500" />
                    <Input
                      id="startTime"
                      name="startTime"
                      type="datetime-local"
                      value={classData.startTime}
                      onChange={(e) =>
                        setClassData({
                          ...classData,
                          startTime: e.target.value,
                        })
                      }
                      className="pl-10 bg-zinc-800 border-zinc-700 text-white"
                      required
                    />
                  </div>
                </div>
              </div>

              <div className="space-y-2">
                <Label
                  htmlFor="description"
                  className="text-sm font-medium text-zinc-300"
                >
                  Description
                </Label>
                <Textarea
                  id="description"
                  name="description"
                  value={classData.description || ""}
                  onChange={(e) =>
                    setClassData({ ...classData, description: e.target.value })
                  }
                  placeholder="Describe what students will learn in this session..."
                  className="bg-zinc-800 border-zinc-700 text-white placeholder-zinc-400"
                  rows={4}
                />
              </div>
            </CardContent>
          </Card>

          {/* Pricing & Fees */}
          <Card className="bg-gradient-to-br from-zinc-900/80 to-black/80 border-zinc-700">
            <CardHeader className="pb-4">
              <CardTitle className="text-xl flex items-center text-white">
                <Tag className="h-5 w-5 mr-2 text-green-400" />
                Pricing & Fees
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <Label
                    htmlFor="registrationFee"
                    className="text-sm font-medium text-zinc-300"
                  >
                    Registration Fee <span className="text-red-500">*</span>
                  </Label>
                  <Input
                    id="registrationFee"
                    name="registrationFee"
                    type="number"
                    min="0"
                    step="0.01"
                    value={classData.registrationFee}
                    onChange={(e) =>
                      setClassData({
                        ...classData,
                        registrationFee: parseFloat(e.target.value),
                      })
                    }
                    placeholder="0.00"
                    className="bg-zinc-800 border-zinc-700 text-white placeholder-zinc-400"
                    required
                  />
                </div>

                <div className="space-y-2">
                  <Label
                    htmlFor="courseFee"
                    className="text-sm font-medium text-zinc-300"
                  >
                    Course Fee <span className="text-red-500">*</span>
                  </Label>
                  <Input
                    id="courseFee"
                    name="courseFee"
                    type="number"
                    min="0"
                    step="0.01"
                    value={classData.courseFee}
                    onChange={(e) =>
                      setClassData({
                        ...classData,
                        courseFee: parseFloat(e.target.value),
                      })
                    }
                    placeholder="0.00"
                    className="bg-zinc-800 border-zinc-700 text-white placeholder-zinc-400"
                    required
                  />
                </div>
              </div>

              <div className="flex items-center justify-between p-4 bg-zinc-800/50 rounded-lg border border-zinc-700">
                <div className="flex items-center space-x-2">
                  <Switch
                    id="registrationEnabled"
                    checked={classData.registrationEnabled}
                    onCheckedChange={(checked) =>
                      setClassData({
                        ...classData,
                        registrationEnabled: checked,
                      })
                    }
                  />
                  <Label
                    htmlFor="registrationEnabled"
                    className="text-sm font-medium text-zinc-300"
                  >
                    Enable Registration
                  </Label>
                </div>
                <div className="text-sm text-zinc-400">
                  Allow students to register for this class
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Thumbnail Upload */}
          <Card className="bg-gradient-to-br from-zinc-900/80 to-black/80 border-zinc-700">
            <CardHeader className="pb-4">
              <CardTitle className="text-xl flex items-center text-white">
                <FileImage className="h-5 w-5 mr-2 text-purple-400" />
                Class Thumbnail
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <p className="text-sm text-zinc-400">
                  Update the image that represents your live class. This will be
                  displayed to students.
                </p>
                <FileUpload
                  onUploadComplete={handleImageUpload}
                  existingImageUrl={classData.thumbnailUrl || ""}
                />
                {classData.thumbnailUrl && (
                  <div className="mt-4 p-4 bg-green-500/10 border border-green-500/20 rounded-lg">
                    <p className="text-sm text-green-400">
                      ✓ Thumbnail uploaded successfully
                    </p>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>

          {/* Additional Settings */}
          <Card className="bg-gradient-to-br from-zinc-900/80 to-black/80 border-zinc-700">
            <CardHeader className="pb-4">
              <CardTitle className="text-xl flex items-center text-white">
                <Settings className="h-5 w-5 mr-2 text-yellow-400" />
                Additional Settings
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <Label
                    htmlFor="currentRaga"
                    className="text-sm font-medium text-zinc-300"
                  >
                    Market Focus
                  </Label>
                  <Input
                    id="currentRaga"
                    name="currentRaga"
                    value={classData.currentRaga || ""}
                    onChange={(e) =>
                      setClassData({
                        ...classData,
                        currentRaga: e.target.value,
                      })
                    }
                    placeholder="e.g., Yaman, Bhairav"
                    className="bg-zinc-800 border-zinc-700 text-white placeholder-zinc-400"
                  />
                </div>

                <div className="space-y-2">
                  <Label
                    htmlFor="currentOrientation"
                    className="text-sm font-medium text-zinc-300"
                  >
                    Skill Level
                  </Label>
                  <Input
                    id="currentOrientation"
                    name="currentOrientation"
                    value={classData.currentOrientation || ""}
                    onChange={(e) =>
                      setClassData({
                        ...classData,
                        currentOrientation: e.target.value,
                      })
                    }
                    placeholder="e.g., Beginner, Intermediate"
                    className="bg-zinc-800 border-zinc-700 text-white placeholder-zinc-400"
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label
                  htmlFor="sessionDescription"
                  className="text-sm font-medium text-zinc-300"
                >
                  Session Highlights
                </Label>
                <Textarea
                  id="sessionDescription"
                  name="sessionDescription"
                  value={classData.sessionDescription || ""}
                  onChange={(e) =>
                    setClassData({
                      ...classData,
                      sessionDescription: e.target.value,
                    })
                  }
                  placeholder="Detailed description of what will be covered in this session..."
                  className="bg-zinc-800 border-zinc-700 text-white placeholder-zinc-400"
                  rows={3}
                />
              </div>

              <div className="flex items-center justify-between p-4 bg-zinc-800/50 rounded-lg border border-zinc-700">
                <div className="flex items-center space-x-2">
                  <Switch
                    id="isActive"
                    checked={classData.isActive}
                    onCheckedChange={(checked) =>
                      setClassData({ ...classData, isActive: checked })
                    }
                  />
                  <Label
                    htmlFor="isActive"
                    className="text-sm font-medium text-zinc-300"
                  >
                    Active Class
                  </Label>
                </div>
                <div className="text-sm text-zinc-400">
                  Make this class available to students
                </div>
              </div>

              {classData.isOnClassroom && (
                <div className="flex items-center justify-between p-4 bg-red-500/10 rounded-lg border border-red-500/20">
                  <div className="flex items-center space-x-2">
                    <Video className="h-5 w-5 text-red-400" />
                    <span className="text-sm font-medium text-red-400">
                      Live Class in Progress
                    </span>
                  </div>
                  <Button
                    type="button"
                    onClick={() => handleToggleClassroom(false)}
                    disabled={isSaving}
                    className="bg-red-600 hover:bg-red-700 text-white"
                  >
                    {isSaving ? (
                      <>
                        <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                        Stopping...
                      </>
                    ) : (
                      "Stop Class"
                    )}
                  </Button>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Submit Button */}
          <div className="flex justify-end gap-4">
            <Button
              type="button"
              variant="outline"
              onClick={() => router.back()}
              className="border-zinc-700 text-zinc-300 hover:bg-zinc-800"
            >
              Cancel
            </Button>
            <Button
              type="submit"
              disabled={isSaving}
              className="bg-green-600 hover:bg-green-700 text-white"
            >
              {isSaving ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Updating...
                </>
              ) : (
                <>
                  <Save className="h-4 w-4 mr-2" />
                  Update Live Class
                </>
              )}
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
}
