import { Course } from "@/type";

export const courses: Course[] = [
  {
    id: "1",
    title: "Complete Web Development with MERN Stack",
    category: "DEVELOPMENT",
    instructor: "Raj Sharma",
    price: 4999,
    image: "/c1.jpg",
    rating: 5,
    reviews: 155,
    lessons: 85,
    students: 1200,
  },
  {
    id: "2",
    title: "UI/UX Design Mastery with Figma",
    category: "DESIGN",
    instructor: "Priya Patel",
    price: 3999,
    image: "/c1.jpg",
    rating: 5,
    reviews: 126,
    lessons: 65,
    students: 890,
  },
  {
    id: "3",
    title: "Advanced Python Programming & Data Science",
    category: "DEVELOPMENT",
    instructor: "Amit Verma",
    price: 5999,
    image: "/c1.jpg",
    rating: 5,
    reviews: 176,
    lessons: 92,
    students: 1500,
  },
  {
    id: "4",
    title: "Full Stack React & Next.js Development",
    category: "DEVELOPMENT",
    instructor: "Rahul Kumar",
    price: 6999,
    image: "/c1.jpg",
    rating: 5,
    reviews: 189,
    lessons: 105,
    students: 2200,
  },
  {
    id: "5",
    title: "DevOps Engineering & Cloud Computing",
    category: "CLOUD",
    instructor: "Ankit Gupta",
    price: 7999,
    image: "/c1.jpg",
    rating: 5,
    reviews: 164,
    lessons: 78,
    students: 950,
  },
  {
    id: "6",
    title: "Mobile App Development with React Native",
    category: "DEVELOPMENT",
    instructor: "Neha Singh",
    price: 5999,
    image: "/c1.jpg",
    rating: 5,
    reviews: 142,
    lessons: 90,
    students: 780,
  },
];
